###
### show-version.yml
###
###   This playbook is a simple example of running Junos CLI commands and returning the standard output
###   NETCONF is not used here.  This technique is really handy for doing simple operational commands
###   like shutting down a device, or 'request system storage' type things
###
###   Make sure you use the '-v' option to see the output, and the '-k' option to get prompted
###   for the user login password.  The username will be your unix login name unless you override it
###   using the -u <user> option
  
---
- hosts: all
  name: Using 'raw' to run Junos CLI "show version" command
  gather_facts: no
  tasks:
          
    - name: get show version
      raw: show version
      register: show_version
      
    - name: display show version
      debug: msg="{{ show_version.stdout }}"
      when: show_version.rc == 0
